sudo: false
caches:
  bundler: true
  directories:
    - node_modules
branches:
  only:
    - gh-pages
language: node_js
node_js:
  - stable
before_install:
  - rvm install 2.2.2
script:
  - 'bundle install'
  - 'make nightly'
